name: Download Image
on: workflow_dispatch
jobs:
  push_to_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |

          docker pull vllm-ascend:v0.11
          docker save vllm-ascend:v0.11 -o vllm_ascend_v0.11.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: vllm_ascend_v0.11.tar
