name: Download Image
on: workflow_dispatch
jobs:
  push_to_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker login registry.example.com
          docker pull vllm-ascend:v0.13
          docker save vllm-ascend:v0.13 -o vllm_ascend_v0.13.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: vllm_ascend_v0.13.tar
